version: 0.72 ({build})

skip_branch_with_pr: true

os:
  - Visual Studio 2017

platform:
  - x64

matrix:
  fast_finish: true  # Stop remaining jobs after a job failure

configuration:
  - Release

clone_folder: C:\CubbyFlow-v0

install:
  - git submodule update --init
  - ps: |
      $env:CMAKE_GENERATOR = "Visual Studio 15 2017 Win64"
      $env:PYTHON = "36-x64"
      $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
      $env:CUBBYFLOW_TASKING_SYSTEM = "CPP11Thread"

before_build:
  - md C:\CubbyFlow-v0\build
  - cd C:\CubbyFlow-v0\build
  - cmake .. -G "%CMAKE_GENERATOR%" -DCUBBYFLOW_TASKING_SYSTEM=CPP11Thread

build:
  project: C:\CubbyFlow-v0\build\CubbyFlow.sln
  parallel: true
  verbosity: normal

after_build:
  - C:\CubbyFlow-v0\build\bin\Release\UnitTests.exe
